### ISSUE TITLE
view log in new tests doesn't work.

### ISSUE THREAD

**Issue by xhdix** [ooni/probe-android#229]
`View Log` doesn't work in new tests in the `web connectivity` section. (About two days)

- There is no problem with old tests. 

- I could not get more information.

- Version: Last

**Comment by bassosimone** [comment]
@xhdix does the proper persist with subsequent betas?

**Comment by xhdix** [comment]
@bassosimone Yes.
An interesting point is that this problem occurred without updating this app.

**Comment by bassosimone** [comment]
@lorenzoPrimi could this be related to https://github.com/ooni/probe/issues/865?

**Comment by lorenzoPrimi** [comment]
Could be, but not for every input.

**Comment by hellais** [comment]
@lorenzoPrimi @bassosimone any ideas on this? Are we able to reproduce this issue?

**Comment by bassosimone** [comment]
I can reproduce this on Android, as follows:

1. enable debug logs

2. run performance

3. see that you miss logs for both

The same happens for Web Connectivity.

**Comment by lorenzoPrimi** [comment]
In the new version the "view  log" button is not shown if the log file is empty. 
I installed the play store version and run performance and I don't see the "view log" button.
I will keep investigating to find the problem.

**Comment by lorenzoPrimi** [comment]
This is the reason why web connectivity don't open logs:
2019-12-24 10:20:48.663 8775-8775/org.openobservatory.ooniprobe W/System.err: Caused by: android.os.TransactionTooLargeException: data parcel size 4333312 bytes
2019-12-24 10:20:48.663 8775-8775/org.openobservatory.ooniprobe W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2019-12-24 10:20:48.663 8775-8775/org.openobservatory.ooniprobe W/System.err:     at android.os.BinderProxy.transact(Binder.java:1127)
2019-12-24 10:20:48.670 8775-8775/org.openobservatory.ooniprobe W/System.err:     at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3754)
2019-12-24 10:20:48.670 8775-8775/org.openobservatory.ooniprobe W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
2019-12-24 10:20:48.670 8775-8775/org.openobservatory.ooniprobe W/System.err: 	... 30 more

**Comment by lorenzoPrimi** [comment]
In case of Performance test, the debug log is written but then when I go to open it it's just not on disk.
Considering that the length of a file is 260354 I wonder if it get deleted by the system

**Comment by lorenzoPrimi** [comment]
@bassosimone what are your thoughts on this?

**Comment by xhdix** [comment]
https://medium.com/@mdmasudparvez/android-os-transactiontoolargeexception-on-nougat-solved-3b6e30597345

**Comment by lorenzoPrimi** [comment]
@xhdix this happens in every Android version, not only nougat. In fact I only get warning, not crashes.
The main question as stated in https://github.com/ooni/probe/issues/865 is if we really want  to load so much data into the memory as we target low end phones.

**Comment by bassosimone** [comment]
@lorenzoPrimi I am still failing to understand what is the specific line of code that causes the exception

**Comment by lorenzoPrimi** [comment]
@bassosimone As I stated in the other thread is `FileUtils.readFileToString` https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/activity/MeasurementDetailActivity.java#L236

**Comment by hellais** [comment]
@lorenzoPrimi can we use a different function for loading the content of a file into a string and parsing the JSON?

> we really want to load so much data into the memory as we target low end phones

1.5 MB of data is not really that much data. I think if your phone doesn't have 1.5 MB of memory you will not be able to load 99% of websites out there.

**Comment by lorenzoPrimi** [comment]
Yeah I guess we should try something else than `FileUtils`

**Comment by lorenzoPrimi** [comment]
After some research I got to this information:
Android 7.0 (Nogat) includes a variety of system and API behaviour changes. Regarding TransactionTooLarge Exception :
```
In Android 7.0, many platform APIs have now started checking for large payloads being sent across Binder transactions, and the system now rethrows TransactionTooLargeExceptions as RuntimeExceptions, instead of silently logging or suppressing them. One common example is storing too much data in Activity.onSaveInstanceState(), which causes ActivityThread.StopInfo to throw a RuntimeException when your app targets Android 7.0.
```
I will try to move the code that reads the file inside the `LogActivity` instead of reading it inside the `ResultActivity` and then passing it forward to the next Activity

**Comment by lorenzoPrimi** [comment]
I managed to move the code inside the `LogActivity` so now there is not a problem of `TransactionTooLargeException` between activities.
The second activity will load and start load the log from the disk.
The real problem is the loading time of the screen (more than 10 seconds and alerts about the app being unresponsive)
And most importantly  the scrolling delay once the screen is loaded due to the eccessive amount of text displayed in a single textview,  basically you can't almost scroll.

**Comment by bassosimone** [comment]
I wonder whether this is the best way to load text from file, then. How do apps that show users large amount of text handle this specific case? Can you put the logs into a GitHub gist and then load the gist into the mobile browser and check whether performance is as sluggish?

**Comment by lorenzoPrimi** [comment]
iOS: using a `WebView` instead of a `TextView` reduces the loading time of the log from 30+ Seconds to 2-3. This solves also https://github.com/ooni/probe/issues/865
Will try the same approach in Android.

**Comment by lorenzoPrimi** [comment]
In Android the same problem (and delays) has been solved in the same way!
The WebView loads large amount of data in a much faster way.
If we go with this approach we need to solve a few things:
- Converting "\n" with "</br>" for logs
- Pretty print json using html tags
- Format html if we want to use a particular font or color

**Comment by lorenzoPrimi** [comment]
- Understand that the webview will be scrollable horizontal and vertical
![Screenshot_1577621666](https://user-images.githubusercontent.com/1616097/71556818-45c2fe00-2a3d-11ea-9aab-cdd354e179ce.png)

**Comment by lorenzoPrimi** [comment]
- Deal with html data inside the log
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-29 at 13 13 57](https://user-images.githubusercontent.com/1616097/71556824-57a4a100-2a3d-11ea-87b3-e1b1d77e291b.png)

**Comment by bassosimone** [comment]
@lorenzoPrimi is there a way to tell the WebView that the content-type is `text/plain`?

**Comment by lorenzoPrimi** [comment]
@bassosimone simple but brilliant solution that will solve all the issues, thanks

**Comment by hellais** [comment]
We should be very careful about injecting untrusted input inside of a WebView, as we are significantly increasing our attack surface.
Is there any way to avoid using a WebView?

If we cannot avoid using a WebView, can we do something to ensure that the content is getting escaped properly and there is no way to get malicious code executed inside of the WebView.

That said, if we can avoid it, we should really avoid it.

**Comment by bassosimone** [comment]
Very good point. So, we're currently forcing `text/plain` but this leaves us vulnerable to refactoring mistakes in which we may mistakenly stop forcing this encoding. Also, it may be that we can still be vulnerable even with forcing test plains because browser's attack surface is large.

**Comment by lorenzoPrimi** [comment]
We cannot use `TextView` as it's too slow or open an external browser as it doesn't have access to the app files so this leaves us only with the webview option.
I don't know anything about the attacks you are talking about but if there is anything to add to the code let me know and I'll do it.

I also removed all the data detection from the webview options
<img width="252" alt="Screenshot 2020-01-01 at 16 37 17" src="https://user-images.githubusercontent.com/1616097/71643087-0999d280-2cb5-11ea-94cf-a80091ab52ad.png">

**Comment by hellais** [comment]
> We cannot use TextView as it's too slow or open an external browser as it doesn't have access to the app files so this leaves us only with the webview option.

Is there perhaps some other component which is for displaying text which we can use?

Or perhaps is there something we can/should do to customise the TextView so that it's more performant?

> I don't know anything about the attacks you are talking about but if there is anything to add to the code let me know and I'll do it.

I am not referring to a specific attack, but I am quite worried of giving untrusted input to a full fledged web browser.
The fact that in your tests above the input was getting interpreted as HTML, makes me quite nervous that if we make some mistake we are exposing our users to potentially several attacks.

Doing just a very little bit of research on this component I find some very scary stuff around too:
https://www.checkmarx.com/2017/11/16/android-webview-secure-coding-practices/

> It is possible for a WebView to access local resources by default, although some restrictions are enforced. These restrictions may vary with the API being used. Here is a list of methods that can be used to change the WebView default permissions:

and:

> setAllowFileAccess – its default value is “true” and allows the WebView to load content from the filesystem. For this a “file:///” schema is used.

Also:

https://www.researchgate.net/publication/221046501_Attacks_on_WebView_in_the_Android_system

Says stuff like:

> WebView provides a number of APIs, allowing code in apps to invoke and be invoked by the JavaScript code within the web pages, intercept their events, and modify those events

My concern is that I don't think we should be running a full browser stack, with parsers for countless data formats a full javascript interpreter and access to OS level APIs, just to display some text!

I worry that the effort to harden and secure this full browser stack is going to be significantly harder (and probably much more error prone) than just going for a simpler options.

@lorenzoPrimi can you see if we can either tweak the TextView to have better performance or investigate if there is some other more minimal component we can use?

**Comment by hellais** [comment]
I am looking at other possible alternatives.

This SO answer looks interesting: https://stackoverflow.com/a/57143651

>You can use Android Paging Library from Jetpack with custom View or RecyclerView
> https://developer.android.com/topic/libraries/architecture/paging
> Implement DataSource abstraction that provides List of data ranges
> Implement Storage abstraction that provides real data (from Database, Network, Files, etc)
> Use RecyclerView and Adapter to display data

and I believe the actual code for it is this: https://github.com/YablokovDmitry/FileView/blob/master/sample/src/main/java/com/ydn/fileviewsample/MainActivity.kt

Maybe also looking at how react-native implements their Text component could be a good idea too.
I found that the native code for it is in here: https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/Libraries/Text/Text/RCTTextView.m
&
https://github.com/facebook/react-native/tree/aee88b6843cea63d6aa0b5879ad6ef9da4701846/Libraries/Text, but I don't understand it too well.
